### PR TITLE
Icon for Fruho

### PR DESCRIPTION
**Pull request by palob**
https://github.com/fruho/fruhoapp

fruho

fruho-numix

### CODE REVIEW

**Comment by Foggalong** [comment]
Is the original design supposed to be a tree?

**Comment by palob** [comment]
Actually I cannot make head or tail of it.

**Comment by Foggalong** [comment]
I've asked :)

**Comment by Foggalong** [comment]
We're going with a tree :+1:

**Comment by palob** [comment]
Alright, I'll look into a tree design.

**Comment by palob** [comment]
How about this?
fruho0

**Comment by Foggalong** [comment]
I like tree no1, it has a networky feel to it :+1:

**Comment by palob** [comment]
Pushed :+1:

**Pull request merged**
