### PR TITLE
linuxdcpp - duplicate to symlink

### PR DESCRIPTION
**Pull request by palob**

### CODE REVIEW

**Comment by Foggalong** [comment]
I'm confused why these are duplicates? The icons do have distinct designs

**Comment by palob** [comment]
``linuxdcpp`` is just slightly distinct because it's the old misaligned design.

**Comment by Foggalong** [comment]
Oh right, they're actually icons for the same app then?

**Comment by palob** [comment]
From what I can see it's those two


https://launchpad.net/linuxdcpp
http://dcplusplus.sourceforge.net/

**Comment by Foggalong** [comment]
In which case yes, keep the distinct icons over a symlink.

**Comment by palob** [comment]
Well, the design isn't distinct. It's just that I did some alignment work for ``DC++.svg`` which ``linuxdcpp.svg`` didn't receive. Prior to that it was aproper duplicate.

**Comment by Foggalong** [comment]
One is [orange](https://github.com/numixproject/circle-core/blob/master/icons/48/linuxdcpp.svg) and one is [green](https://github.com/numixproject/circle-core/blob/master/icons/48/DC++.svg) though?

**Comment by palob** [comment]
Oh, alright, will recolour DC++.svg then :)

**Pull request closed without merging**
