### PR TITLE
Fixes #3347

### LINKED ISSUE #3347: Chrome Web Store icon missing
This is the last missing one on my system I promise! :) Unfortunately I cannot provide a link for the chrome webstor webapp since its its the store itself missing the icon. The application ID and icon ID is: **chrome-ahfgeienlihckogmohjhadlkjgocpleb-Default**

The original app icon looks like this:
chrome internetes aruhaz

Based on your other software center icons something like this would look great I think:
softwarecenter

Thanks again for the great work you guys do!

### PR DESCRIPTION
**Pull request by palob**
Fixes #3347 

chrome-ahfgeienlihckogmohjhadlkjgocpleb-default

### CODE REVIEW

**Comment by Foggalong** [comment]
The colours of the yellow segment and the bag are a little too similar. Possibly try a different bag colour?

**Comment by palob** [comment]
Desaturated it a bit.
chrome-ahfgeienlihckogmohjhadlkjgocpleb-default

**Comment by Foggalong** [comment]
That's a bit better, but still not great. Possibly a slightly darker yellow and lighter bag at the same time?

**Comment by palob** [comment]
chrome-ahfgeienlihckogmohjhadlkjgocpleb-default

**Comment by palob** [comment]
Pushed this:
chrome-ahfgeienlihckogmohjhadlkjgocpleb-default

**Pull request merged**
