### PR TITLE
Bodhi distro icon

### PR DESCRIPTION
**Pull request by palob**
distributor-logo-bodhi

### CODE REVIEW

**Comment by Foggalong** [comment]
Less gradients please! They're okay when used sparingly, but aren't strictly part of the symbol design guidelines.

**Comment by palob** [comment]
W/o the circle gradient?
distributor-logo-bodhi

**Comment by Foggalong** [comment]
Gradients on both bits preferably - imo they're not strictly needed to get the icon to work

**Comment by palob** [comment]
Like this?
distributor-logo-bodhi

**Pull request closed without merging**
