### PR TITLE
Added World of Tanks icon

### PR DESCRIPTION
**Pull request by codefuhrer**
See #3280

### CODE REVIEW

**Comment by palob** [comment]
Hi, thanks for the PR.
The symbol is a bit big. It shouldn't exceed a size of 26px X 26px (28x28 for some exceptions or 30x30 for circular symbols).

In order not to appear blurry all horizontal/vertical straight lines need to be aligned to the pixel grid (toggled with ``#`` in Inkscape).
blurry

**Comment by codefuhrer** [comment]
Ok, will do.

This icon's bottom part is optically lighter, than the top. Should it be exactly 26x26px anyway?

**Comment by codefuhrer** [comment]
Hm. Some parts are too far from any grid intersection:

Screenshot

If I just align everything to the grid, it'll look like BS. What should I do?

**Comment by palob** [comment]
You need to find a size symbol size where it works. I'm sure you will :) I've done a lot of icons and there's always been a way to get the alignment right without sacrificing too much of the symbol characteristics.

It can take a few shots sometimes.

**Comment by Foggalong** [comment]
@codefuhrer Do you have plans to update this pull request?

**Comment by codefuhrer** [comment]
@Foggalong Not really, cannot find the right position. 
I don't mind if you want to close it.

**Comment by Foggalong** [comment]
No problem, since it's your first icon and we've done all this messing around with repo structures I'll merge it and fix it up :+1:

**Comment by codefuhrer** [comment]
Cool, looks much better after your fixes :hushed:
Thanks!

**Pull request merged**
