### PR TITLE
Next cleanup/alignment spree

### PR DESCRIPTION
**Pull request by palob**
Removed ``plague2.svg`` which I had introduced accidentally earlier.

### CODE REVIEW

**Comment by Foggalong** [comment]
All good apart from pxsc and qtsixa. The symbols are based on the playstation controller layout and the button arrangement in pxsc drifts away from that a bit

**Comment by palob** [comment]
The new ``pcsx-icon`` is ``epsxe`` recoloured and doesn't differ greatly from how it looked before?

Should I base ``pcsx-icon`` on ``qtsixa`` or just arrange the buttons on the right hand in cross manner?

**Comment by Foggalong** [comment]
Just arrange the rhs buttons for pcsx in a cross for now and we'll possibly come back to this in future

**Comment by palob** [comment]
:+1:

**Comment by Foggalong** [comment]
:+1:

**Pull request merged**
