### PR TITLE
Icons for RationalPlan

### PR DESCRIPTION
**Pull request by Jacajack**
Hi everybody!
I made icons for RationalPlan as requested in #3270 

selection_837

I hope everything is ok :)

### CODE REVIEW

**Comment by palob** [comment]
It's a little bit blurry in some places. Con you find a configuration where the pixel grid alignment is better to get a really crips symbol. For instance the shape I've selected below will get crisper by just moving it some 0.4 px down.

selection

The lowermost path gets crisper by changing the height to 4 and moving it to an integer Y position.
The head is crisper with integer dimensions and x/y positioning.

**Comment by Jacajack** [comment]
@palob Thanks for advice, is that better now?

I rounded width, height, X and Y of each path to integers, so it should be better (except from arm part(?), because I assumed it's ok).
By the way, I thought that only straight horizontal and vertical lines should be aligned with the grid, so why does that blur happen?

**Comment by palob** [comment]
:+1: Better now.

Proper alignment is important for curved (but almost vertical/horizontal) and ellipsoid shapes as well. 

Basically in order to get an icon as crisp as possible you need to get as many of the"pixel grid squares" in Inkscape (each representing a single pixel on the screen) to be filled with only one colour (or predominantly one colour). 
If the edge between two differently coloured shapes runs through one of those "squares" so that there are two different colours in it the pixel on screen will be displayed with an interpolated colour (interpolation based on area fraction of the colours).
Now if an object isn't properly aligned to the pixel grid (meaning the "colour edge" isn't congruent with pixel boundaries) there will be a line of interpolated colouring around this object which is the root for blurriness.

**Comment by Jacajack** [comment]
Oh... That makes sense...
Now I don't know how I could not figure that out myself.

I will try to take more care of it next time
Thanks  :)

**Comment by palob** [comment]
One "warning" in this regard: Inkscape grid = pxel grid isn't cast in stone.

It might not be set up that way with every SVG file out there.

Actually Inkscape lets you set the grid lines' intervall and direction freely in the document options.

**Comment by Jacajack** [comment]
I understand.
I think I'm going to make checklist from all the mistakes I made, not to bother you too much, when I contribute in future.
Thank you for explanation once more :)

**Comment by palob** [comment]
I'll probably add more detailed, illustrated step-by-step instructions as to how to create a Numix Circle icon to the wiki some time.
Thanks you plan on continuing to contribute :)

**Pull request merged**
