### PR TITLE
web-bandcamp.svg

### PR DESCRIPTION
**Pull request by palob**
It's for the Nuvolaplayer webapp. Needs a symlink ``nuvolaplayer3-bandcamp``.
web-bandcamp

### CODE REVIEW

**Comment by Foggalong** [comment]
Could you try adding a pale brown background to this?

**Comment by palob** [comment]
web-bandcamp-brown1

**Comment by Foggalong** [comment]
go with option 3 :smile:

**Comment by palob** [comment]
Pushed :grinning:

**Comment by Foggalong** [comment]
@palob is the symlink to use `-` or `_`?

**Comment by palob** [comment]
Ouch, typo again indeed. It's ``_``.

**Comment by Foggalong** [comment]
Cool, no problem! :)

**Pull request merged**
